runtime: nodejs18

env: standard

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: production
  PORT: "8080"
  VITE_API_URL: ${VITE_API_URL}

automatic_scaling:
  min_instances: 1
  max_instances: 3

skip_files:
  - ^node_modules$
  - ^\.git$
  - ^\.env$
  - ^\.env\.local$
