runtime: nodejs18

env: standard

entrypoint: node dist/index.js

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  NODE_ENV: production
  PORT: "8080"
  MONGODB_URI: ${MONGODB_URI}
  JWT_SECRET: ${JWT_SECRET}
  EMAIL_USER: ${EMAIL_USER}
  GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
  FRONTEND_URL: ${FRONTEND_URL}

automatic_scaling:
  min_instances: 1
  max_instances: 5

beta_settings:
  cloud_sql_instances: ${CLOUD_SQL_INSTANCE}
